Vagrant.configure("2") do |config|
  config.vm.box = "djangocon/base"
  config.vm.box_url = "file:///c:/DjangoCon/base.box"

  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 22, host: 8022

  # forget about the insecure key (small speedup)
  config.ssh.insert_key = false
  
#  config.vm.provision "shell", inline: <<SCRIPT
#	cp -r /vagrant/pip-cache /root/.cache/
#	rm -rf /root/.cache/pip
#	mv /root/.cache/pip-cache /root/.cache/pip
#	chown -R root:root /root/.cache/pip
#	echo "Defaults	always_set_home" >> /etc/sudoers.d/home
#SCRIPT
end
