Vagrant.configure("2") do |config|
  config.vm.box = "djangocon/base"
  config.vm.box_url = "file:///c:/DjangoCon/base.box"

  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 22, host: 8022

  # forget about the insecure key (small speedup)
  config.ssh.insert_key = false

  # disable default shared folder (small speedup)
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
