Vagrant.configure("2") do |config|
  config.vm.box = "djangocon/base"
  config.vm.box_url = "file:///c:/DjangoCon/base.box"

  config.vm.network "forwarded_port", guest: 5432, host: 5432, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 22, host: 8022, host_ip: "127.0.0.1"

  # forget about the insecure key (small speedup)
  config.ssh.insert_key = false

  # disable default shared folder (small speedup)
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # enable external connections for PostgreSQL
  config.vm.provision "shell", inline: <<-EOF
    echo "listen_addresses='*'" >> /etc/postgresql/9.5/main/postgresql.conf
    echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/9.5/main/pg_hba.conf
    service postgresql restart
  EOF
end
